## KNN Regression Training using Mean Squared Error

Predicting the unamed columns

In [1]:
import pandas as pd
import numpy as np
from shutil import copyfile
import os

In [2]:
src = "../data/bigtable.csv"
dst = "./bigtable.csv"
if os.path.exists(dst):
    os.remove(dst)
copyfile(src, dst)

'./bigtable.csv'

In [3]:
df = pd.read_csv(dst)
df.tail()

,datetime,pm25,type,sensor,station_id,x,y,population,dist-mroads,dist-setl,...,cos_year,TEMP,DEW,SKY,VIS,ATM,Wind-Dir,Wind-Rate,AQI_class,AQI_VALUE
105393,2019-10-27 18:00:00+00:00,2.0,AirNow,ND,"[{name=US EPA AirNow, url=http://www.airnow.go...",38.89475,-76.95343,3.510231,0.093,-0.216,...,0.436651,25.61,20.01,22000.0,16000.0,1008.01,310.0,4.6,Good,6.493506
105394,2019-10-27 18:00:00+00:00,5.0,AirNow,ND,"[{name=US EPA AirNow, url=http://www.airnow.go...",39.11440,-77.10690,0.094436,0.378,0.405,...,0.436651,25.61,20.01,22000.0,16000.0,1008.01,310.0,4.6,Good,16.233766
105395,2019-10-27 18:00:00+00:00,2.0,AirNow,ND,"[{name=US EPA AirNow, url=http://www.airnow.go...",39.05530,-76.87830,0.094436,0.378,0.405,...,0.436651,25.61,20.01,22000.0,16000.0,1008.01,310.0,4.6,Good,6.493506
105396,2019-10-27 18:00:00+00:00,7.0,AirNow,ND,"[{name=US EPA AirNow, url=http://www.airnow.go...",38.87516,-77.01282,3.510231,0.093,-0.216,...,0.436651,25.61,20.01,22000.0,16000.0,1008.01,310.0,4.6,Good,22.727273
105397,2019-10-27 08:00:00+00:00,5.6,AirNow,ND,"[{name=US EPA AirNow, url=http://www.airnow.go...",38.77170,-77.10890,3.400232,0.118,0.000,...,0.436651,16.75,16.15,366.0,8047.0,9999.99,90.0,1.5,Good,18.181818

In [4]:
from pandas.plotting import scatter_matrix
#scatter_matrix(df, alpha=0.2, figsize=(6, 6), diagonal='kde')

This will give the dimension of 2-d Array

In [7]:
from numpy import set_printoptions
df2=df.drop(["datetime", "type", "sensor", "station_id", "x", "y"], axis=1)

In [8]:
df2 = df2.dropna()

In [9]:
df2.head()

,pm25,population,dist-mroads,dist-setl,dist-coast,dist-forest,slope,elevation,dayofweek,sin_day,...,cos_year,TEMP,DEW,SKY,VIS,ATM,Wind-Dir,Wind-Rate,AQI_class,AQI_VALUE
0,52.33,54.04969,0.072,-1.541,2.792,1.596,1.0,29.0,2,-0.707107,...,-0.591261,21.11,16.11,99999.0,16000.0,1021.81,50.0,3.6,USG,123.860000
1,43.76,54.04969,0.072,-1.541,2.792,1.596,1.0,29.0,3,-0.707107,...,-0.605056,20.01,16.71,99999.0,16000.0,1021.31,90.0,3.6,USG,106.720000
2,11.41,54.04969,0.072,-1.541,2.792,1.596,1.0,29.0,3,-0.866025,...,-0.696376,24.45,10.65,22000.0,16093.0,1013.15,330.0,3.6,Good,37.045455
3,10.24,54.04969,0.072,-1.541,2.792,1.596,1.0,29.0,3,-0.965926,...,-0.696376,25.05,10.65,22000.0,16093.0,1012.65,320.0,5.7,Good,33.246753
4,9.45,54.04969,0.072,-1.541,2.792,1.596,1.0,29.0,3,-1.000000,...,-0.696376,25.01,10.61,22000.0,16000.0,1012.61,320.0,5.7,Good,30.681818

In [10]:
from sklearn.neighbors import KNeighborsRegressor

array = df2.values
print(len(array))
print(len(array[0]))

X = array[:,2:16]
Y = array[:,1]

neigh = KNeighborsRegressor(n_neighbors=2)
neigh.fit(X, Y)

Y_target = neigh.predict(X)

105224
22

In [11]:
Y_target

array([54.04969024658203, 54.04969024658203, 54.04969024658203, ...,
       0.09443560987710953, 3.5102307796478267, 3.400232315063477],
      dtype=object)

In [12]:
np.mean((Y_target - Y)**2)

# mse
#np.mean always computes an arithmetic mean, and has some additional options for input and output (e.g. what datatypes to use, where to place the result).

1.8039201490914452